### ISSUE TITLE
Change of plans

### ISSUE THREAD

**Issue by Swartz27** [Swartz27/xray-oxygen-rendering#1]
Turns out I'm not a total moron after all, I don't have to re-write it from scratch just do as Xottab tried to tell me which is to break it down one piece of time.

BTW, I have the present to end all presents coming your way within a couple hours ;)  However you will need to have Windows 10 and a card that supports DX12 level features. Trust me: very worth it!

**Comment by Swartz27** [comment]
lmao, looks like I was so stoned I forgot about it entirely XD  The present is done already but I need to kinda re-install Windows atm due to a bug. I have the present on another drive, so when I'm back up and running I will upload it into a new branch...unless I'm so stoned I forget again.

**Comment by ForserX** [comment]
Hm...

**Comment by Swartz27** [comment]
LOL!
Look guys, I'm useless. Here, this: https://github.com/Microsoft/DirectXShaderCompiler
Compile, and your life will be complete. I'll get around to giving you guys the same thing,

Anyway, what you want is the dxcompiler_bridge.dll thing: with that you can literally make any Directx11 game utilize Directx12 features. I've tried it on many games, and stalker, and all of them look fantastic now. It's a night and day difference. 
Please note that this is of course only for Windows 10 (though I would argue that if you like gaming, Windows 10 is downright GOOD for the first time ever as of the newest dev-release.

I have no clue why I was keeping it secret and going to offer it as a "present" but now you know how fucked I am in the head XD  Maybe I should ease up on the weed.

**Comment by Swartz27** [comment]
BTW, I know it seems like I'm overstating things, I'm really not. It's that awesome.

I also feel there is now currently zero point in doing a DX12 renderer until their new real-time raytracing reaches release phase, at which point then would be a good time to implement it.

**Comment by Swartz27** [comment]
@ForserX https://drive.google.com/open?id=12Iu9tjwsu0RO6DLxZYAlPSdcsRUDmcot

I finally uploaded it XD  Here's the deal: see the d3dcompiler_46 dll? Just rename that to whatever which game you are modifying uses by defaullt (yes, replace it, after backing up as some games are a little picky).
